CREATE TABLE `post` (
	`post_pk` INT(11) NOT NULL AUTO_INCREMENT,
	`image` VARCHAR(1000) NULL DEFAULT NULL,
	`description` VARCHAR(500) NULL DEFAULT NULL,
	`address` VARCHAR(500) NULL DEFAULT NULL,
	`title` VARCHAR(500) NULL DEFAULT NULL,
	`areacode` INT(11) NULL DEFAULT NULL,
	`content_id` INT(11) NULL DEFAULT NULL,
	`cat3` VARCHAR(500) NULL DEFAULT NULL,
	`content_type_id` INT(11) NULL DEFAULT NULL,
	`mapx` DOUBLE NULL DEFAULT NULL,
	`mapy` DOUBLE NULL DEFAULT NULL,
	PRIMARY KEY (`post_pk`)
)
COMMENT='여행 post'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
